QuanLyBanHang/Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSiteBanHang.Models;
using PagedList;

namespace WebSiteBanHang.Controllers
{
    public class TimKiemController : Controller
    {
        //
        // GET: /TimKiem/
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        [HttpGet]
        public ActionResult KQTimKiem(string sTuKhoa,int? page)
        {
            if (Request.HttpMethod != "GET")
            {
                page = 1;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            //tìm kiếm theo ten sản phẩm
            var lstSP = db.SANPHAMs.Where(n => n.TenSP.Contains(sTuKhoa));
            ViewBag.TuKhoa = sTuKhoa;
            return View(lstSP.OrderBy(n=>n.TenSP).ToPagedList(pageNumber,pageSize));
        }
        [HttpPost]
        public ActionResult LayTuKhoaTimKiem(string sTuKhoa)
        {
            //Gọi về hàm get tìm kiếm
            return RedirectToAction("KQTimKiem", new {@sTuKhoa=sTuKhoa});
        }
        public ActionResult KQTimKiemPartial(string sTuKhoa)
        {
            //tìm kiếm theo ten sản phẩm
            var lstSP = db.SANPHAMs.Where(n => n.TenSP.Contains(sTuKhoa));
            ViewBag.TuKhoa = sTuKhoa;
            return PartialView(lstSP.OrderBy(n=>n.DonGia));
        }
     
	}
}

QuanLyBanHang/Views/Layout/HeaderTopPartital.cshtml
@using WebSiteBanHang.Models
<div class="header-top">
    <div class="container">
        <div class="search">
            @*Tạo form submit về action tìm kiếm*@
            @using (Html.BeginForm("LayTuKhoaTimKiem", "TimKiem"))
            {
            <input type="text" name="sTuKhoa" placeholder="Nhập tên sản phẩm cần tìm..">
                <input type="submit" value="Tìm kiếm">
            }
        </div>
        <div class="header-left">
            <ul>
                @if (Session["TaiKhoan"] != null && Session["TaiKhoan"] != "")
                {
                    ThanhVien tv = (ThanhVien)Session["TaiKhoan"];
                        <li>Chào @tv.HoTen </li>
                    @Html.ActionLink("Đăng xuất","DangXuat","Home")
                }
                else
                {
                    <li style=" display: inline;"><a id="btnDangNhap" class="lock" href="#">Đăng nhập</a></li>
                  <li style=" display: inline;"><a class="lock" href="@Url.Action("DangKy","Home")">Đăng ký</a></li>
       
                }
                 <li>
           
                </li>

            </ul>
            @*Chèn partial view giỏ hàng vào layout( Tách icon giỏ hàng sang 1 partial view mới)*@
            @Html.Action("GioHangPartial","GioHang")
            <div class="clearfix"> </div>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>

<link href="~/Content/css/style_form_dangnhap.css" rel="stylesheet" />
    <br />
    @*Tạo 1 div bên ngoài chứa div login-form *@
    <div id="popup_login">
        <div class="login-form" id="login-form">
            <div style="clear:both;text-align:right;margin-bottom:0;">
                <span id="close-form" class="btn btn-danger">X</span>
            </div>
            <h2>Đăng nhập</h2>
            <div class="form-info">
                @using (Ajax.BeginForm("DangNhap", "Home", new AjaxOptions {InsertionMode=InsertionMode.Replace,UpdateTargetId="ThongBao" }))
                { 
                  
                    <input class="email TaiKhoan" name="txtTenDangNhap" placeholder="Tên đăng nhập" required="" type="text">
                    <input class="password MatKhau" name="txtMatKhau" placeholder="Mật khẩu" required="" type="password">
                    <p><a href="#">Quên mật khẩu?</a></p>
                         <h3 style="font-weight:bold;color:red;text-align:left;" id="ThongBao"> </h3>
                    <ul class="login-buttons">
                        <li><input value="Đăng nhập" type="submit" id="btnDangNhap1"></li>
                        <li><a href="#" class="hvr-sweep-to-left">Đăng ký</a></li>
                         
                    </ul>
                 
                }

            </div>
        </div>
    </div>


<style>


    #close-form {
        color: white;
    }


    #login-form {
        background: #3a3a46;
        cursor: pointer;
    }
    /*css cho phần div popup_login*/
    #popup_login {
        position: fixed;
        top: 0;
        left: 0;
        width:100%;
        height:100%;
        background-color: rgba(0,0,0,.5);
        z-index: 9999;
        display: none;
    }
    ul {
        text-align:left;
    }
</style>
@*Sử dụng jquery hiển thị popup đăng nhập*@
<script type="text/javascript">
    //Hiển thị popup_login
    $("#btnDangNhap").click(function () {
        $("#popup_login").show();
    });
    //Ẩn đi popup_login
    $("#close-form").click(AnForm);

    //Định nghĩa function ẩn form
    function AnForm() {
        $("#popup_login").hide();
    }
    //Ví dụ về lấy giá trị từ textbox
    $("#btnDangNhap1").click(function () {
        var TaiKhoan = $(".TaiKhoan").val();
        var MatKhau = $(".MatKhau").val();
        //alert("Tài khoản:" + TaiKhoan + "\n Mật khẩu:" + MatKhau);
        if (TaiKhoan == "") {
            alert("Lỗi");
            return;
        }
    });

</script>